--- #YAML:1.0
name:               Text-Median
version:            0.02
abstract:           Perl extension for determining the set median of a set of strings
author:
    - Leigh  Metcalf <leigh@local>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Module::Runtime:  0.006
    Test::Warn:       0.11
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
